### Create Admin
POST http://localhost:3000/admin
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbklEIjoxLCJlbWFpbCI6ImFkbWluMUBleGFtcGxlLmNvbSIsImV4cCI6MTc0NzA1MDQzNSwicm9sZSI6ImFkbWluIn0.1Ts2gXWyci0rLP22ALA0FUabwRi_wjiTbQHNefYp1Ms

{
  "email": "admin1@example.com",
  "password": "somepass",
  "totp_secret":""
}

### Get Admin by ID
GET http://localhost:3000/admin/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbklEIjoxLCJlbWFpbCI6ImFkbWluMUBleGFtcGxlLmNvbSIsImV4cCI6MTc0Njc1OTY2Niwicm9sZSI6ImFkbWluIn0.SUtZwdDkFyoDQYyzrxaj7buz8ud4hi57FGA2weypXnU

### Update Admin
PUT http://localhost:3000/admin/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbklEIjoxLCJlbWFpbCI6ImFkbWluMUBleGFtcGxlLmNvbSIsImV4cCI6MTc0NzYzNjQ1Miwicm9sZSI6ImFkbWluIn0.vl1YR8HjNJt59z850BkARwZI7McB3OskpvoWzT__xtE

{
  "email": "admin2@example.com",
  "password": "securepass",
  "totp_secret": ""
}

### List Admins
GET http://localhost:3000/admin?limit=10&offset=0
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbklEIjoxLCJlbWFpbCI6ImFkbWluMUBleGFtcGxlLmNvbSIsImV4cCI6MTc0NzcxNTIwMiwicm9sZSI6ImFkbWluIn0.WU_nSxmVa77d8KBc9zTxS1yoIBmb5ZGAEqFyL3ORHl0
