### Create Candidate
POST http://localhost:3000/candidate
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbklEIjoyLCJlbWFpbCI6ImFkbWluMkBleGFtcGxlLmNvbSIsImV4cCI6MTc0NjQ0NTcyNywicm9sZSI6ImFkbWluIn0.9msec4uS7vVWaMIpC47jV1ne-iO_kvvC-bWJRt4UjX8

{
  "citizen_id": "123-457",
  "election_id": 4,
  "profile_path": "/images/candidate1.png",
  "bio": "Committed to public service.",
  "post": "Mayor"
}

### Get Candidate by ID
GET http://localhost:3000/candidate/1

### Update Candidate
PUT http://localhost:3000/candidate/1
Content-Type: application/json

{
  "citizen_id": "123-456",
  "election_id": 2,
  "profile_path": "/images/candidate1_updated.png",
  "bio": "Updated bio info.",
  "post": "Mayor"
}

### Delete Candidate
DELETE http://localhost:3000/candidate/1

### List candidate
GET http://localhost:3000/candidate?limit=10&offset=0
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbklEIjoyLCJlbWFpbCI6ImFkbWluMkBleGFtcGxlLmNvbSIsImV4cCI6MTc0NjQ0NTcyNywicm9sZSI6ImFkbWluIn0.9msec4uS7vVWaMIpC47jV1ne-iO_kvvC-bWJRt4UjX8
