### Create Citizen
POST http://localhost:3000/citizen
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbklEIjoxLCJlbWFpbCI6ImFkbWluMUBleGFtcGxlLmNvbSIsImV4cCI6MTc0Njc1OTY2Niwicm9sZSI6ImFkbWluIn0.SUtZwdDkFyoDQYyzrxaj7buz8ud4hi57FGA2weypXnU

{
  "citizenship_id": "123-456",
  "full_name": "Jhon Doe",
  "date_of_birth": "1990-01-01",
  "birth_place": "Kathmandu",
  "permanent_address": "Kathmandu"
}

### Get Citizen by ID
GET http://localhost:3000/citizen/123-459
Accept: application/json

### Update Citizen
PUT http://localhost:3000/citizen/123-456
Content-Type: application/json

{
  "full_name": "John Doe Updated",
  "date_of_birth": "1990-01-01",
  "birth_place": "Pokhara",
  "permanent_address": "456 New St, Kathmandu"
}

### Delete Citizen
DELETE http://localhost:3000/citizen/123-456

### List citizen
GET http://localhost:3000/citizen?limit=10&offset=0
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbklEIjoxLCJlbWFpbCI6ImFkbWluMUBleGFtcGxlLmNvbSIsImV4cCI6MTc0NzA1MDQzNSwicm9sZSI6ImFkbWluIn0.1Ts2gXWyci0rLP22ALA0FUabwRi_wjiTbQHNefYp1Ms

