### Reset Password
POST http://localhost:3000/auth/forgot
Content-Type: application/json

{
  "voter_card_id": "1111111111",
  "citizenship_id": "11-11-11-11111",
  "totp":"440356",
  "new_password":"somenewpass"
}
