### User Login
POST http://localhost:3000/auth/user
Content-Type: application/json

{
  "citizenship_id": "123-456",
  "voter_card_id": "VC-001",
  "password": "securepassword",
  "totp":"557189"
}


### Admin Login
POST http://localhost:3000/auth/admin
Content-Type: application/json

{
  "email": "admin1@example.com",
  "password": "securePassword123",
  "totp_code": "593451"
}


