### Create Voter Card
POST http://localhost:3000/forgot
Content-Type: application/json

{
  "voter_card_id": "VC-001",
  "citizenship_id": "123-456",
  "totp": "111111",
  "new_password": "somenewpassword"
}
