### Create User  
POST http://localhost:3000/user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbklEIjoxLCJlbWFpbCI6ImFkbWluMUBleGFtcGxlLmNvbSIsImV4cCI6MTc0NzcxNTIwMiwicm9sZSI6ImFkbWluIn0.WU_nSxmVa77d8KBc9zTxS1yoIBmb5ZGAEqFyL3ORHl0

{
  "citizenship_id": "11-11-11-11111",
  "voter_card_id": "1111111111",
  "password": "somepass",
  "totp_secret": "",
  "photos": ""
}

### Get User by ID  
GET http://localhost:3000/user/0
Accept: application/json

### Update User  
PUT http://localhost:3000/user/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbklEIjoyLCJlbWFpbCI6ImFkbWluMkBleGFtcGxlLmNvbSIsImV4cCI6MTc0NjQ0NTcyNywicm9sZSI6ImFkbWluIn0.9msec4uS7vVWaMIpC47jV1ne-iO_kvvC-bWJRt4UjX8

{
  "citizenship_id": "123-456",
  "voter_card_id": "VC-001",
  "password": "somepass",
  "totp_secret": "",
  "photos": "{\"selfie\": \"newbase64\"}"
}

### Delete User  
DELETE http://localhost:3000/user/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbklEIjoyLCJlbWFpbCI6ImFkbWluMkBleGFtcGxlLmNvbSIsImV4cCI6MTc0NjQ0NTcyNywicm9sZSI6ImFkbWluIn0.9msec4uS7vVWaMIpC47jV1ne-iO_kvvC-bWJRt4UjX8

### List user  
GET http://localhost:3000/user?limit=10&offset=0
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbklEIjoxLCJlbWFpbCI6ImFkbWluMUBleGFtcGxlLmNvbSIsImV4cCI6MTc0NzcxNTIwMiwicm9sZSI6ImFkbWluIn0.WU_nSxmVa77d8KBc9zTxS1yoIBmb5ZGAEqFyL3ORHl0

# ### Lookup by CitizenshipID + VoterCardID  
# GET http://localhost:3000/user/lookup?citizen_id=123-456&voter_card_id=
# Accept: application/json
