### Create User  
POST http://localhost:3000/user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbklEIjoyLCJlbWFpbCI6ImFkbWluMkBleGFtcGxlLmNvbSIsImV4cCI6MTc0NjQ0NTcyNywicm9sZSI6ImFkbWluIn0.9msec4uS7vVWaMIpC47jV1ne-iO_kvvC-bWJRt4UjX8

{
  "citizenship_id": "123-458",
  "voter_card_id": "VC-001",
  "password": "securepassword",
  "totp_secret": "",
  "photos": "{\"selfie\": \"base64string\"}"
}

### Get User by ID  
GET http://localhost:3000/user/0
Accept: application/json

### Update User  
PUT http://localhost:3000/user/3
Content-Type: application/json

{
  "citizenship_id": "123-456",
  "voter_card_id": "VC-001",
  "password": "somethingsomething",
  "totp_secret": "NEWSECRET789",
  "photos": "{\"selfie\": \"newbase64\"}"
}

### Delete User  
DELETE http://localhost:3000/user/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbklEIjoyLCJlbWFpbCI6ImFkbWluMkBleGFtcGxlLmNvbSIsImV4cCI6MTc0NjQ0NTcyNywicm9sZSI6ImFkbWluIn0.9msec4uS7vVWaMIpC47jV1ne-iO_kvvC-bWJRt4UjX8

### List user  
GET http://localhost:3000/user?limit=10&offset=0
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbklEIjoyLCJlbWFpbCI6ImFkbWluMkBleGFtcGxlLmNvbSIsImV4cCI6MTc0NjQ0NTcyNywicm9sZSI6ImFkbWluIn0.9msec4uS7vVWaMIpC47jV1ne-iO_kvvC-bWJRt4UjX8

# ### Lookup by CitizenshipID + VoterCardID  
# GET http://localhost:3000/user/lookup?citizen_id=123-456&voter_card_id=
# Accept: application/json
